apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  my-nginx
  labels:
    name:  my-nginx
spec:
  template:
    metadata:
      annotations:
        tke.cloud.tencent.com/vpc-eni-cni-ip: "true"
      labels:
        name:  my-nginx
    spec:
      containers:
      - image:  nginx:alpine
        name:  my-nginx
        resources:
          requests:
            cpu: "1"
            memory: "1024M"
          limits:
            cpu: "1"
            memory: "1024M"
        lifecycle:
          preStop:
            exec:
              # nginx -s quit gracefully terminate while SIGTERM triggers a quick exit
              command: ["nginx","-s","quit"]
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: data
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'wget https://raw.githubusercontent.com/Kevin-Qiu/config-init/master/config.sh;chmod 777 config.sh;./config.sh']
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: data
      volumes:
        - name: data
          emptyDir: {}